### ISSUE TITLE
Information on how the design studio is now affected by tags in the template & update colour tag docs

### ISSUE THREAD

**Issue by AidanThreadgold** [createdotnet/wdk#1]
New design studio now only shows settings based on the tags you've used for: 
- Fonts (base font tag needs documenting)
- Wallpapers
- Logos
- Colours (the introduction of new colour tags needs documenting)

**Comment by mattgreenfield** [comment]
And I guess we should remove the info about there being 6 specific colour tags that we use?

**Comment by mattgreenfield** [comment]
Color docs updates are now live.

**Comment by AidanThreadgold** [comment]
Wallpaper docs added in 1.1 branch

**Comment by AidanThreadgold** [comment]
Don't think we need to do anything for the logos now.
Fonts added in v1.1 branch
