### ISSUE TITLE
WDK example templates out of date

### ISSUE THREAD

**Issue by AidanThreadgold** [createdotnet/wdk#14]
We'd be better of open sourcing Little Devil or something which has a wider use of WDK tags.

**Comment by Dayjo** [comment]
Agreed, however, I worry about having an over complicated example

**Comment by mattgreenfield** [comment]
Part of the tutorials could be;

> We're going to run through how to make a basic template from scratch... You can download the end product here. Alternatively, why not check out the source code for our 'Little Devil' template.

Or maybe that kind of walkthrough over complicates it.
