### ISSUE TITLE
New font tags missing

### ISSUE THREAD

**Issue by AidanThreadgold** [createdotnet/wdk#15]
New font tags have not been documented and neither has the `WDK:base:css:fonts` tag.

---
1. Include the following tag `<style><!--WDK:base:css:fonts--></style>` in your `<head>` element
2. Include this following css file `<link rel="stylesheet" href="/_assets/css/templates/icon-fonts/icon-fonts.min.css?20141119" media="screen" />`

**Comment by AidanThreadgold** [comment]
Also need to document that you need this css file:
`<link rel="stylesheet" href="/_assets/css/templates/icon-fonts/icon-fonts.min.css?20141119" media="screen" />` @createdotmatt

**Comment by AidanThreadgold** [comment]
Do you think we could include that CSS file automatically in the `base:assets:css` tag?

**Comment by mattgreenfield** [comment]
I wonder if people want to disable the option for users to change the font in the design studio? Maybe to use a google font?

**Comment by AidanThreadgold** [comment]
Could do that by not including the font tag - have added a line about it
