### ISSUE TITLE
Sidecolumns - column count tag and others missing

### ISSUE THREAD

**Issue by AidanThreadgold** [createdotnet/wdk#16]
I couldn't find any docs on the "wdk_column_count_x" body class + tag, or any docs on "if left sidecolumn", "if right sidecolumn".

If it's there... where is it?

**Comment by mattgreenfield** [comment]
See pull #43 for the column count tag.

I wasn't aware that the 'if left' tags existed, doesn't look like they are on the google docs spreadsheat of supported tags. Also, are we moving away from left / right and towards primary / secondary?

**Comment by AidanThreadgold** [comment]
`<!--WDK:if:sideLeft-->`  
`<!--WDK:if:sideRight-->`  

I'd say just stick with left/right for this version and worry about that next
