### ISSUE TITLE
Explain legacy css files

### ISSUE THREAD

**Issue by AidanThreadgold** [createdotnet/wdk#17]
`WDK:base:assets` tag includes a "legacy" css file. 
- What does this file do? (overwriting certain CSS styles)
- Why do I need it?

**Comment by mattgreenfield** [comment]
I think this is kind of tied up with #2 

One of the reasons we use the legacy.css file is to include the non responsive grid.

**Comment by AidanThreadgold** [comment]
Ah yeh, I agree )

**Comment by benjaminparry** [comment]
Fluid grid abstracted for WDK users https://github.com/createdotnet/dyos_html/pull/699

Explanation in the docs and intent to change, does that fix this issue?

**Comment by AidanThreadgold** [comment]
I think so :)
