### ISSUE TITLE
Restructure documentation

### ISSUE THREAD

**Issue by AidanThreadgold** [createdotnet/wdk#19]
I've been attempting to create a WDK template using the docs - and my conclusion is it isn't possible. Numerous tags are missing and little to no explanation on some of the things we've added over the last year (fonts/base assets/grid etc etc). 

I'm opening a general discussion on how best to structure the WDK docs. Currently we've got "Glossary" and "Tutorials" (which I find confusing) and personally prefer something like the Wordpress Codex or Tumblr theme docs - https://www.tumblr.com/docs/en/custom_themes.

@createdotmatt @Dayjo @benjaminparry @Create-Ed

**Comment by Dayjo** [comment]
I agree it's not clear enough. I do kind of like the tumblr thing, but that's a lot of information all on one page

**Comment by AidanThreadgold** [comment]
Ah yes - sorry should have been clearer. Only referenced Tumblr as I think it's a good example of a concise navigation structure, and concise documentation for the individual tags.

**Comment by mattgreenfield** [comment]
The issue I find is that we have a lot of tutorial kind of stuff splattered around the site, some in 'getting started' and some in the glossary.

I think we should decide if 'glossary' and 'tutorials' are to stay (I think they should) and then move things to better fit those, making the glossary a very basic tag and description with a link to any relevant tutorial.

I'm happy to do all of this restructuring.

I tried using the docs a month or two ago and made a trello board of the infomation that I wanted that wasn't readily available etc. It (of course) on a trello board... https://trello.com/b/L9iYluld/wdk-thoughts

**Comment by Dayjo** [comment]
What we kind of discussed yesterday was that the home page is totally unnecessary and it should just be the getting started guide which gives you a simple explanation and example of how to create your first template. That way we get rid of getting started completely, and tutorials can be more specific.

**Comment by EdBailey** [comment]
Also, the glossary isn't in any way a glossary :)

**Comment by AidanThreadgold** [comment]
+1 to Joel and Matt.
The "Glossary" should become an "Index" of the tags available and explanation of what it does/needed for - simply called "Tags" perhaps.

**Comment by benjaminparry** [comment]
@AidanThreadgold ~ Happy the issue is resolved?

**Comment by AidanThreadgold** [comment]
:+1:
