### ISSUE TITLE
HelpCentre board doesn't exist any more?

### ISSUE THREAD

**Issue by EdBailey** [createdotnet/wdk#23]
The homepage and support pages reference a 'designated board' on the HelpCentre for WDK questions but, as far as I can tell, this doesn't exist anymore. Does this need updating to reference something else/need removing?
If the 'board' is still there, I personally feel it should be a direct link rather than a vague reference to it existing.

**Comment by Dayjo** [comment]
Should probably just link here, this is something we need to discuss as to the level of support offered on the WDK.

**Comment by AidanThreadgold** [comment]
This has been removed now
