### ISSUE TITLE
Lowlight tag is not documented

### ISSUE THREAD

**Issue by mattgreenfield** [createdotnet/wdk#25]
We have a page for the highlight color tag but the lowlight tag is missing. 

This is a valid tag right? @Dayjo

**Comment by AidanThreadgold** [comment]
Yeh - all colour formatting tags:

WDK:color:tint
WDK:color:highlight
WDK:color:lowlight
WDK:color:invert
WDK:color:brighten
WDK:color:darken
WDK:color:bestvisible
WDK:color:blend
