### ISSUE TITLE
WDKEditor - preview doesn't always refresh when editing files

### ISSUE THREAD

**Issue by AidanThreadgold** [createdotnet/wdk#28]

**Comment by Dayjo** [comment]
This is normally mostly to do with caching CSS files.

**Comment by benjaminparry** [comment]
@joel ~ re: our discussion about adding a persistent cache-buster to the WDK editor for CSS files. Would that be a reliable fix for this issue?

I’ll do some further testing to see if there are any other issues centring around refreshing the preview.

**Comment by Dayjo** [comment]
Well, I'd already tried cache busting to no avail, but yeah technically that should do it. The only issue with "the preview not updating" has been cached css rather than it actually failing to reload the frame, however that could be an issue I guess?
