### ISSUE TITLE
Guide for taking Page Builder into account when making templates

### ISSUE THREAD

**Issue by AidanThreadgold** [createdotnet/wdk#3]
To include: 
1. Diagrams/explanations/code of how we are reflowing the content 
2. Potentially outline the feature road map for page builder (increases the need for something like #4 )

@benjaminparry @createdotmatt

**Comment by benjaminparry** [comment]
I think we need to adopt a wdk-first approach to the css with PageBuilder, whether that is included with https://github.com/createdotnet/boilerplate or another method entirely.
