### ISSUE TITLE
Custom WDK - Font's don't change

### ISSUE THREAD

**Issue by AidanThreadgold** [createdotnet/wdk#31]
1. Set custom WDK template as your template
2. Change fonts -> expected: fonts don't change
3. Save
4. Edit WDK index file and click Save -> expected: fonts changed 

Believe this is because `<!--WDK:base:css:fonts-->` is being evaluated on save, and not loading in the font stacks dynamically.

**Comment by Dayjo** [comment]
Fix looks good

**Comment by AidanThreadgold** [comment]
Fix is now live.
