### ISSUE TITLE
Parts of the site you can/can't WDK via custom template

### ISSUE THREAD

**Issue by AidanThreadgold** [createdotnet/wdk#33]
Can WDK in a custom template:
1. Header (index.html)
2. Footer (index.html)
3. Sidecolumns (index.html)
4. Main menu (index.html)
5. Social Profiles / Cards / Newsletter (index.html)
6. Blog Index (blog.html) - **no wdk tags documented for this**
7. Blog Post (blog_post.html)
8. Blog Category (blog_category.html)

Can't:
1. Events
2. Contact
3. Guestbook
4. Account login/sign up
5. 'My Account' view
6. Shop Basket (Has internal WDK support in guava)
7. Shop Checkout (Has internal WDK support in guava)
8. Shop Thankyou (Has internal WDK support in guava)
9. Shop - Category View (Has internal WDK support)
10. Shop - Category Product Listing (Has internal WDK support)
11. Shop - Product View (Has internal WDK support)
12. Related Products / Customer also bought

**Comment by Dayjo** [comment]
Blog isn't supported by the blog system yet is it? Same as the shop stuff, it's WDK'd but not public yet

**Comment by AidanThreadgold** [comment]
If you added a blog.html file to your tempalte, it would use that file...

**Comment by Dayjo** [comment]
Oh shit yeah?? I didn't realise that'd been implemented, awesome!
