### ISSUE TITLE
Wallpaper on custom wdk

### ISSUE THREAD

**Issue by AidanThreadgold** [createdotnet/wdk#34]
Not sure if this is the right tag, but it's the only one I could find about wallpapers - `<!--WDK:display:bgimage-->` which only outputs the background image URL. 

If I then turn the wallpaper off, or change it (after initially setting it) - the wallpaper doesn't turn off or change.

**Comment by Dayjo** [comment]
There's a wallpaper one which does all the tiling stuff as well I believe.

**Comment by AidanThreadgold** [comment]
@createdotmatt  - is it this one: `<!--WDK:templateoption:templatebg-->` ? 

Same issue as https://github.com/createdotnet/wdk/issues/31 with that tag

**Comment by mattgreenfield** [comment]
yup, thats the tag that is on our templates.

```
    body { 
        <!--WDK:templateoption:templatebg-->  
        background-color: <!--WDK:display:pagebg-->;
        font-family: <!--WDK:display:font-->;
        color: <!--WDK:display:bodytxt-->;
    }
```
