### ISSUE TITLE
Universal body helper classes WDK tag

### ISSUE THREAD

**Issue by benjaminparry** [createdotnet/wdk#35]
I think it would be helpful for maintenance and consistence if we had something live `<!--WDK:template:helper-classes-->` that would output what we currently have in each template (below).

```
<body class="wdk_columnCount_<!--WDK:column:count--><!--WDK:if:sideRight--> has-complementary--primary<!--WDK:endif--><!--WDK:if:sideLeft--> has-complementary--secondary<!--WDK:endif--><!--WDK:if:hasShop--> has-shop<!--WDK:if:plugin:shop:property:use_basket--> has-basket<!--WDK:endif--><!--WDK:if:plugin:useraccount:property:shoploginlink--> has-login<!--WDK:ifnot:plugin:useraccount:isloggedin--><!--WDK:else--> is-logged-in<!--WDK:endif--><!--WDK:endif--><!--WDK:if:plugin:shop:hasBasket--> has-basket-contents<!--WDK:endif--><!--WDK:endif--> template-rwd">
```

As a reminder, these helper classes are used for styling hooks for css.

// @AidanThreadgold @createdotmatt

**Comment by AidanThreadgold** [comment]
@createdotmatt That'd solve the need for the `wdk_column_count` thing in the category layouts... 
@benjaminparry Would having `template-rwd` be appropriate on custom WDKs?

**Comment by benjaminparry** [comment]
It depends if we’re using that class for widgets like owl slider.
