### ISSUE TITLE
Sidebar/content width tags

### ISSUE THREAD

**Issue by EdBailey** [createdotnet/wdk#38]
It would be helpful if templates were able to define their sidebar/content widths using some tags. e.g. Most templates have sidebars at 250px and content has a max width of 1000px but others have smaller sidebars etc.

I'm mainly looking at this from the perspective of generating responsive image tags.

**Comment by AidanThreadgold** [comment]
`<!--WDK:column:width:250-->` but we're moving away from that because of responsive... On most of our templates in `lap` view, side column items become width 33%

**Comment by EdBailey** [comment]
Yeah, what it really needs is a way to define each breakpoint in px or % or whatever :/

Also, I thought they became 25%...

**Comment by mattgreenfield** [comment]
I know that the new templates are 20%, so its not always the same.

**Comment by AidanThreadgold** [comment]
We're be defining the breakpoints (as per what the design studio uses) in the docs later on - could just work of the assumption side columns will always be 20 - 33% ?
