### ISSUE TITLE
Clarification about what jQuery version we're using and what is using jQuery

### ISSUE THREAD

**Issue by AidanThreadgold** [createdotnet/wdk#4]
See - `/pages/tutorials/11using-jquery.html`

**Comment by Dayjo** [comment]
There is a paragraph at the bottom of this page regarding versions. But yeah definitely should list things that use jquery.

**Comment by AidanThreadgold** [comment]
FYI this page makes reference to a tag that doesn't exist ""

**Comment by Dayjo** [comment]
This might mean `headinfo`
