### ISSUE TITLE
Cached published custom CSS/JS files not being purged on published

### ISSUE THREAD

**Issue by AidanThreadgold** [createdotnet/wdk#41]
Internal issue number: 166994000 
Raised by http://whoatemycrayons.com

**Comment by Dayjo** [comment]
How it used to work with rackspace was that when you pushed a new file / update it'd purge the cache. There was a problem specifically with CSS files in that their API didn't auto determine mime types so it over-cached it, we manually sent the mime type and it fixed it (Then they updated their system to not be so stupid).
