### ISSUE TITLE
Document how to set your version

### ISSUE THREAD

**Issue by mattgreenfield** [createdotnet/wdk#46]

**Comment by AidanThreadgold** [comment]
Where do you think this should go? 
http://developers.create.net/wdk/tutorials/the-header.html ?

**Comment by mattgreenfield** [comment]
In [this pull request](https://github.com/createdotnet/wdk/compare/v1.1) I've added it as `_tutorials/setting-your-version.md` but I'm open to offers!

I was wondering about putting a 'latest version' header on the home page or something.

**Comment by AidanThreadgold** [comment]
Ah cool, yeh i'm fine with that :)
