### ISSUE TITLE
Email to send to WDK users about 1.1 changes

### ISSUE THREAD

**Issue by AidanThreadgold** [createdotnet/wdk#48]
Dear X,

We're contacting you because you are using a template built with the [Web Designer's Kit](http://www.create.net/web_designers_kit.phtml) ("WDK").

Today we have released version 1.1 of the WDK. This version includes a number of minor changes relating to the use of the WDK and we recommend you take a look at the [change log](http://developers.create.net/wdk/changelog.html) for the full details. 

Please note - these changes will not affect your published site. If you do not wish to upgrade your WDK version, no action is required, but if you do read how to [set your version](http://developers.create.net/wdk/tutorials/setting-your-version.html). If your template was made by someone other than yourself, we recommend you forward this email on to them.

Regards,
Create.net Product Team

**Comment by mattgreenfield** [comment]
Cool. Maybe worth mentioning something like

> nothing will change on your existing site. If you do not wish to upgrade, no action is required. Check out the (tutorial)[/linkkk] on updating to the latest version.

and possibly 

> If you do not know what this means, please contact the person who made the template for you.

**Comment by Dayjo** [comment]
:+1:  Probably will want to pass it by Danielle

**Comment by benjaminparry** [comment]
Added a link to how you can set your version http://developers.create.net/wdk/tutorials/setting-your-version.html
