### ISSUE TITLE
HTML5shiv.js build, tag and documentation needed

### ISSUE THREAD

**Issue by benjaminparry** [createdotnet/wdk#51]
Precursor to [Google Code closing Jan 2016](http://google-opensource.blogspot.co.uk/2015/03/farewell-to-google-code.html), we should probably start hosting an html5shiv.js build.

> **HTML5shiv**
> This script is the defacto way to enable use of HTML5 sectioning elements in legacy Internet Explorer

Example:

```
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
```

Now maintained on github https://github.com/aFarkas/html5shiv

This is included on all of our responsive templates which are using new HTML5 markup and something that should be documented and providing a tag for the WDK users.

Is it worth forking to https://github.com/createdotnet?

@AidanThreadgold

**Comment by AidanThreadgold** [comment]
Probably better to do this sooner than later - don't really have much of an opinion on forking it tbh - would we be customising it at all?

**Comment by benjaminparry** [comment]
Just a straight up build + minify, just thought it might be easier to update if it was a fork and sits outside of our codebase being a 3rd party library.

**Comment by Dayjo** [comment]
If only sub repos ...
