### ISSUE TITLE
Extend the WDK tags to support `or/and` in if statements

### ISSUE THREAD

**Issue by benjaminparry** [createdotnet/wdk#61]
In certain instances it would be useful to add `or/and` logic to the WDK tags, e.g. set a grid layout if either one or more statements are true.

Would this be possible?

@AidanThreadgold @createdotmatt @Dayjo

**Comment by AidanThreadgold** [comment]
It'd be possible - but the actual WDK users would have to write for that would be horrific

**Comment by Dayjo** [comment]
With @AidanThreadgold here, I'm dubious about extending the WDK tags to be more 'programmy' - that's not really what templating systems SHOULD be (but always end up being). Another option to 'ors' might just be some more specific tags. Could you give us some examples where you've wanted to / needed to do an Or like statement? 

For instance if you wanted to do  `<!--WDK:if:basket:empty--> OR <!--WDK:ifnot:hasShop-->` .. we should just make basket:empty already check that they have a shop so you shouldn't need the OR.

**Comment by benjaminparry** [comment]
The shop for instance, where one option is to hide the quantity column if the quantity option is off.

Currently:

```
<!--WDK:if:plugin:tax:should_show-->colspan="4"<!--WDK:else-->colspan="3"<!--WDK:endif-->
```

I want `colspan="4"` if either tax or quantity is showing and `colspan="3"` if neither are.

Perhaps my programatically logic skills aren’t up to scratch…

**Comment by Dayjo** [comment]
We could just make a tag in these situations.
`colspan="<!--WDK:plugin:shop:basket_table_colspan-->"`

I guess maybe a way to set variables, but then you'd have to do the horrible logic anyways somewhere else.
