### ISSUE TITLE
Related Posts is not dynamic

### ISSUE THREAD

**Issue by mattgreenfield** [createdotnet/wdk#8]
It would be nice for the related posts and the end of each post to work based on a tag system. Maybe a section for related WDK tags / glossary, and another for related tutorials.

I've created a branch named 'tags' but it appears to be a lot more difficult without the use of jekyll plugins (which github pages does not support).

Anyway, any thoughts and ideas appreciated!

**Comment by Dayjo** [comment]
You still against building locally?

**Comment by mattgreenfield** [comment]
Well there's beauty in the simplicity of editing a markdown file and pushing the change. Would be nice not to add an extra step just for this.
