### ISSUE TITLE
404 Links 

### ISSUE THREAD

**Issue by Dayjo** [createdotnet/wdk#9]
Here's a list of broken links that @rkimber discovered on the WDK docs;

| Dead Link | Status | ON PAGE |
| --- | --- | --- |
| http://developers.create.net/wdk/pages/support/01how-it-works.html | 404 | http://developers.create.net/wdk/getting-started/01before-you-start.html |
| http://developers.create.net/wdk/pages/glossary/glossary.html | 404 | http://developers.create.net/wdk/tutorials/index.html |
| http://developers.create.net/wdk/pages/tutorials/tutorials.html | 404 | http://developers.create.net/wdk/glossary/index.html |
| http://developers.create.net/wdk/pages/tutorials/14page-builder.html | 404 | http://developers.create.net/wdk/changelog.html |
| http://developers.create.net/wdk/tutorials/12conditional-tags.html | 404 | http://developers.create.net/wdk/tutorials/01requirements-restrictions.html |
| http://developers.create.net/wdk/tutorials/08the-header.html | 404 | http://developers.create.net/wdk/tutorials/02the-basics.html |
| http://developers.create.net/wdk/tutorials/09the-footer.html | 404 | http://developers.create.net/wdk/tutorials/02the-basics.html |
| http://developers.create.net/wdk/tutorials/07the-basics.html | 404 | http://developers.create.net/wdk/tutorials/03the-header.html |
| http://developers.create.net/wdk/pages/glossary/08header-images/01header-image.html | 404 | http://developers.create.net/wdk/tutorials/03the-header.html |
| http://developers.create.net/wdk/pages/glossary/03side-columns/01id.html | 404 | http://developers.create.net/wdk/tutorials/03the-header.html |
| http://developers.create.net/wdk/tutorials/02side-columns-content-width.html | 404 | http://developers.create.net/wdk/tutorials/12converting-to-wdk.html |
| http://developers.create.net/wdk/tutorials/03advanced-colour-functions.html | 404 | http://developers.create.net/wdk/tutorials/12converting-to-wdk.html |
| http://developers.create.net/wdk/pages/tutorials/12conditional-tags.html | 404 | http://developers.create.net/wdk/glossary/02conditional/01page-file-name-is.html |
| http://developers.create.net/wdk/glossary/02conditional/18header-x-is-gif.html | 404 | http://developers.create.net/wdk/glossary/02conditional/05else.html |
| http://developers.create.net/wdk/glossary/02conditional/13header-x.html | 404 | http://developers.create.net/wdk/glossary/02conditional/12header-x-is-png.html |
| http://developers.create.net/wdk/pages/tutorials/10header-images | 404 | http://developers.create.net/wdk/glossary/08header-images/02header-x-width.html |
| http://developers.create.net/wdk/glossary/11basics/pages/tutorials/08the-header.html | 404 | http://developers.create.net/wdk/glossary/11basics/08header-start.html |

**Comment by mattgreenfield** [comment]
ah thats a shame, I'll put it on my to do list. @AidanThreadgold could we get Travis to check for these?

**Comment by AidanThreadgold** [comment]
@createdotmatt Tried to get this working first time round, but couldn't - didn't have that much time to look into it properly though - https://github.com/gjtorikian/html-proofer
